#!/bin/bash
set -o nounset -o errexit -o pipefail
mkdir -p /tmp/rstudio-temp
cd /tmp/rstudio-temp
apt-get update -y
apt-get install -y gdebi libapparmor1
wget -q https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.3.959-amd64.deb
wget -q http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
gdebi -n libssl1.0.0_1.0.2n-1ubuntu5.3_amd64.deb
gdebi -n rstudio-server-1.3.959-amd64.deb
ln -sfn /usr/lib/rstudio-server /usr/local/lib/rstudio-server 
chown -R root:root /usr/lib/rstudio-server
cd ~
rm -rf /tmp/rstudio-temp
echo "www-frame-origin=any" >> /etc/rstudio/rserver.conf
chown ubuntu:ubuntu /etc/rstudio/rserver.conf
#Make rmarkdown::render work outside of rstudio. https://github.com/rstudio/rmarkdown/blob/master/PANDOC.md
ln -sfn /usr/lib/rstudio-server/bin/pandoc/pandoc /usr/local/bin
ln -sfn /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc /usr/local/bin
rm -rf /var/lib/apt/lists/*
